name: 'default'
projection_mode: 'orthogonal'
sdf: True
debug: False
training:
  data_name: 'mvp'
  gpus: [0]
  test_gpus: [0]
  lr_G: 0.001
  lr_C: 0.001
  weight_decay: 0.0
  momentum: 0.0
  optim: 'Adam'
  schedule: [3, 6]
  gamma: 0.1
  resume: True
  resume_path: ''
  test_mode: False
  thresh: 0.
  train_bsize: 1
  val_bsize: 1
  test_bsize: 1
  num_threads: 8
  num_epoch: 10
  freq_plot: 0.05
  freq_show_train: 0.1
  freq_show_val: 0.2
  freq_eval: 0.1
  freq_save: 0.01
  n_save_epoch: 1
  max_n_iter: 100000
  out_dir: out
  mcube_res: 256
  clean_mesh: False
  input_keys: [
    'rgb',
    'normal',
    'canon_points',
    'canon_surf_normal',
    'canon_smpl_joints',
    'canon_smpl_vert',
    'posed_points',
    'posed_smpl_joints',
    'posed_surf_normal',
    'projected_points',
    'projected_smpl_vert',
    'projected_surf_normal',
    'smpl_faces',
    'labels',
    'depth',
    'vT',
    'calib',
  ]
dataset:
  mvp_obj_dir: '/media/liaotingting/usb3/Dataset/MVP-CANO200'
  mvp_smpl_dir: '/media/liaotingting/usb3/Dataset/data_sample'
  mvp_syn_dir: '/media/liaotingting/usb3/Dataset/MVP-Synthetic'
  mvp_sample_dir: '/media/liaotingting/usb3/liaotingting/mvphuman_samples/da-pose'
  thuman_data_dir: '/media/liaotingting/usb3/Dataset/THuman2.0'
  thuman_syn_dir: '/media/liaotingting/usb3/Dataset/THuman2.0-Synthetic'
  thuman_sample_dir: '/media/liaotingting/usb3/Dataset/THuman2.0/samples'
  rp_syn_dir: '/media/liaotingting/usb3/Dataset/render_people64/synthetic'
  rp_obj_dir: '/media/liaotingting/usb3/Dataset/render_people64/fit'
  rp_smpl_dir: '/media/liaotingting/usb3/Dataset/render_people64/fit'
  rp_sample_dir: '/media/liaotingting/usb3/Dataset/render_people64/samples'
  buff_syn_dir: '/media/liaotingting/usb3/Dataset/BUFF/synthetic'
  buff_obj_dir: '/media/liaotingting/usb3/Dataset/BUFF/synthetic'
  th_type: 'train'
  overfit: False
  input_size: 512
  num_surface: 8192
  num_perturb: 8192
  num_bbox: 8192
  num_sample_color: 0
  sigma: 0.05
  b_min: [-1.8, -1.8, -1.8]
  b_max: [1.8, 1.8, 1.8]
  num_views: 1
  aug: True
  aug_bri: 0.4
  aug_con: 0.4
  aug_sat: 0.4
  aug_hue: 0.4
  aug_blur: 1.0
  random_flip: True
  random_scale: True
  random_trans: True
  input_im: 'normal'
  train_n_rotation: 360
  train_n_action: 5
  test_n_rotation: 4
  test_n_action: 4
net:  
  gtype: 'HGPIFuNet'
  netIMF: 'resnet18'
  norm: 'group'
  norm_mlp: 'batch'
  norm_color: 'group'
  hg_down: 'ave_pool'
  conv1: [7, 2, 1, 3]
  conv3x3: [3, 1, 1, 1]
  num_stack: 4
  num_hourglass: 2
  hourglass_dim: 256
  skip_hourglass: False
#  mlp_dim: [280, 1024, 512, 256, 128, 1]
#  res_layers: [2, 3, 4]
  mlp_dim: [3, 512, 512, 512, 512, 512, 512, 1]
  res_layers: [4]
  geometric_init: False
  radius_init: 1.5
  octaves_pe: 0
  lambda_sdf: 1.0
  lambda_occ: 1.0
  lambda_igr_surf_sdf: 0.
  lambda_igr_off_sdf: 0.
  lambda_grad: 1.
  lambda_nml: 1.
  arch_occ_lambda1: 0.1
  arch_occ_lambda2: 0.3
  no_residual: True
  use_attention: False
  transfomer_kwargs: {
    'dim': 280,
    'depth': 2,
    'heads': 4,
    'mlp_dim': 256,
    'dropout': 0.1,
    'emb_dropout': 0.1
  }
  loss_type: []
  no_im_feat: False
  geo_feat_dict: {'canon': [], 'posed': [], 'projected': []}
  point_feat_dim: 72
  n_harmonic_functions: 4
  use_filter: True
  use_normal: False
  use_depth: False
smpl:
  model_path: 'data/smpl_related/models'
  model_type: 'smpl_vitruvian'
  gender: 'neutral'
  use_face_contour: False
  vitruvian_angle: 25

